name: Release to Snapcraft
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  snapcraft_publish:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish Snapcraft
      env:
        SNAPCRAFT_BUILD_ENVIRONMENT: host
        RELEASE_TAG: ${{ github.ref }}
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_LOGIN }}
      working-directory: ./packages/snap/
      run: |
        export MAGIC=$SNAP/usr/share/file/magic.mgc
        sudo apt update
        sudo apt -y install git python3-pip python3-setuptools
        sudo apt -y install snapd
        sudo snap install snapcraft --classic
        snapcraft login
        snapcraft
        version=$(echo ${RELEASE_TAG} | sed 's#^.*v##g')
        snapcraft upload --release=stable dotdrop_${version}_amd64.snap
