name: Release to Snapcraft
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: build-snap
      with:
        path: ./packages/snap
    - uses: actions/upload-artifact@v3
      with:
        name: dotdrop
        path: ${{ steps.build-snap.outputs.snap }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: dotdrop
        path: .
    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_LOGIN }}
      with:
        snap: ${{needs.build.outputs.snap-file}}
        release: 'stable'
